# Generated by Django 5.1.5 on 2026-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('decimals', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='assets_asse_symbol_71b57b_idx'), models.Index(fields=['is_active'], name='assets_asse_is_acti_7e009b_idx')],
            },
        ),
    ]
