# Generated by Django 5.1.5 on 2026-09-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_fields_and_network'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_asset_symbol_71b57b_idx',
        ),
        migrations.RenameIndex(
            model_name='assetnetwork',
            new_name='assets_asse_asset_i_1e08f5_idx',
            old_name='assets_assetn_asset_i_4d5b19_idx',
        ),
        migrations.RenameIndex(
            model_name='assetnetwork',
            new_name='assets_asse_status_4bfd82_idx',
            old_name='assets_assetn_status_2c1dbb_idx',
        ),
    ]
