# Generated by Django 5.1.5 on 2026-09-01 07:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTCQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('requested_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('quoted_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('quoted_total', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otc_quotes', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otc_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTCDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otc_deals', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='otc.otcquote')),
            ],
        ),
        migrations.AddIndex(
            model_name='otcquote',
            index=models.Index(fields=['user', 'status'], name='otc_otcquot_user_id_4ce4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='otcquote',
            index=models.Index(fields=['asset', 'status'], name='otc_otcquot_asset_i_b5b6b9_idx'),
        ),
    ]
