# Generated by Django 5.1.5 on 2026-09-01 07:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('deposit_address', models.CharField(blank=True, default='', max_length=255)),
                ('network', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'asset'], name='wallets_wal_user_id_8808aa_idx'), models.Index(fields=['asset', 'network'], name='wallets_wal_asset_i_ef165a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_user_wallet_asset')],
            },
        ),
    ]
