# Generated by Django 5.1.5 on 2026-09-15 12:11

import uuid

from django.db import migrations, models


def populate_reference_numbers(apps, schema_editor):
    Transaction = apps.get_model(
        "transactions",
        "Transaction",
    )

    for transaction in Transaction.objects.filter(
        reference_number__isnull=True,
    ).iterator():
        transaction.reference_number = (
            f"TX-{uuid.uuid4().hex[:20].upper()}"
        )
        transaction.save(
            update_fields=["reference_number"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(
                max_length=50,
                null=True,
                blank=True,
            ),
        ),

        migrations.RunPython(
            populate_reference_numbers,
            migrations.RunPython.noop,
        ),

        migrations.AlterField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(
                max_length=50,
                unique=True,
                db_index=True,
            ),
        ),
    ]