# Generated by Django 5.1.5 on 2026-09-15 12:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_assets_asset_symbol_71b57b_idx_and_more'),
        ('transactions', '0002_prepare_transaction_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='network',
            new_name='network_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='required_confirmations',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='toman_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('toman_deposit', 'Toman Deposit'), ('toman_withdrawal', 'Toman Withdrawal'), ('crypto_deposit', 'Crypto Deposit'), ('crypto_withdrawal', 'Crypto Withdrawal'), ('fee', 'Fee'), ('refund', 'Refund'), ('reversal', 'Reversal')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='transaction_referen_2a6622_idx'),
        ),
    ]
