# Generated by Django 5.1.5 on 2026-10-05 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_assets_asset_symbol_71b57b_idx_and_more'),
        ('transactions', '0003_rename_network_transaction_network_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_referen_2a6622_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_user_status_idx',
            old_name='transaction_user_id_9cef77_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_txid_idx',
            old_name='transaction_txid_7f6a8b_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type'], name='txn_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'created_at'], name='txn_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order_id'], name='txn_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='unique_transaction_user_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('toman_amount__gte', 0)), name='transaction_toman_amount_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='transaction_fee_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('confirmations__gte', 0)), name='transaction_confirmations_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('required_confirmations__gte', 0)), name='transaction_required_confirmations_gte_zero'),
        ),
    ]
