# Generated by Django 5.1.5 on 2026-09-01 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('otp_requested', 'OTP requested'), ('otp_verified', 'OTP verified'), ('otp_failed', 'OTP failed'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('registration_success', 'Registration success'), ('logout', 'Logout'), ('password_change', 'Password change'), ('kyc_update', 'KYC update'), ('security_alert', 'Security alert')], default='login_success', max_length=32),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
