# Generated by Django 5.1.5 on 2026-09-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_loginhistory_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('otp_requested', 'OTP requested'), ('otp_verified', 'OTP verified'), ('otp_failed', 'OTP failed'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('registration_success', 'Registration success'), ('logout', 'Logout'), ('password_change', 'Password change'), ('kyc_update', 'KYC update'), ('security_alert', 'Security alert'), ('two_factor_enabled', 'Two-factor enabled'), ('two_factor_disabled', 'Two-factor disabled')], default='login_success', max_length=32),
        ),
        migrations.CreateModel(
            name='TwoFactorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two-Factor Credential',
                'verbose_name_plural': 'Two-Factor Credentials',
            },
        ),
    ]
