# Generated by Django 5.1.5 on 2026-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('otp_requested', 'OTP requested'), ('otp_verified', 'OTP verified'), ('otp_failed', 'OTP failed'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('registration_success', 'Registration success'), ('logout', 'Logout'), ('password_change', 'Password change'), ('password_reset_success', 'Password reset success'), ('kyc_update', 'KYC update'), ('security_alert', 'Security alert'), ('two_factor_enabled', 'Two-factor enabled'), ('two_factor_disabled', 'Two-factor disabled'), ('anti_phishing_created', 'Anti-phishing created'), ('anti_phishing_updated', 'Anti-phishing updated'), ('anti_phishing_deleted', 'Anti-phishing deleted')], default='login_success', max_length=32),
        ),
    ]
