# Generated by Django 5.1.5 on 2026-09-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
    ]
