# Generated by Django 5.1.5 on 2026-09-01 07:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], default='limit', max_length=12)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'), models.Index(fields=['asset', 'status'], name='orders_orde_asset_i_fa01a3_idx')],
            },
        ),
    ]
