# Generated by Django 5.1.5 on 2026-09-15 12:16

import apps.orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_assets_asset_symbol_71b57b_idx_and_more'),
        ('orders', '0003_order_timeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_order_number, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
