# Generated by Django 5.1.5 on 2026-09-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
