# Generated by Django 5.1.5 on 2026-09-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_email_verified_at_user_pending_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_kyc_sta_e3d46c_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
    ]
