# Generated by Django 5.1.5 on 2026-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_accounts_us_kyc_sta_e3d46c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anti_phishing_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
