# Generated by Django 5.1.5 on 2026-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_anti_phishing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawal_whitelist_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
