# Generated by Django 5.1.5 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_withdrawal_whitelist_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('registration', 'Registration'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('withdrawal_address', 'Withdrawal Address')], max_length=20),
        ),
    ]
