# Generated by Django 5.1.5 on 2026-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='iranianbank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='iranianbank',
            name='sheba_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3),
        ),
    ]
