# Generated by Django 5.1.5 on 2026-10-04 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_iranianbank_is_active_iranianbank_sheba_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCardPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_legacy', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(db_index=True, default='manual', max_length=50)),
                ('source_url', models.URLField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_card_prefixes', to='accounts.iranianbank')),
            ],
            options={
                'ordering': ['-prefix'],
                'indexes': [models.Index(fields=['bank', 'prefix', 'is_active'], name='accounts_ba_bank_id_495957_idx'), models.Index(fields=['bank', 'is_active', 'is_legacy'], name='accounts_ba_bank_id_ccf945_idx')],
                'unique_together': {('bank', 'prefix')},
            },
        ),
        migrations.CreateModel(
            name='BankVerificationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('iban_bank_code', models.CharField(blank=True, default='', max_length=3)),
                ('iban_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('card_luhn_valid', models.BooleanField(default=False)),
                ('iban_checksum_valid', models.BooleanField(default=False)),
                ('card_bank_known', models.BooleanField(default=False)),
                ('iban_bank_known', models.BooleanField(default=False)),
                ('banks_match', models.BooleanField(default=False)),
                ('card_ownership_verified', models.BooleanField(default=False)),
                ('iban_ownership_verified', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('invalid_card', 'Invalid Card'), ('invalid_iban', 'Invalid IBAN'), ('unknown_card_prefix', 'Unknown Card Prefix'), ('unknown_iban_bank', 'Unknown IBAN Bank'), ('bank_mismatch', 'Bank Mismatch'), ('ownership_failed', 'Ownership Failed'), ('verified', 'Verified')], default='invalid_card', max_length=30)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_verification_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_ba_user_id_a1c6f3_idx'), models.Index(fields=['result', 'created_at'], name='accounts_ba_result_072b5d_idx'), models.Index(fields=['card_prefix', 'card_last4'], name='accounts_ba_card_pr_0573a5_idx')],
            },
        ),
    ]
