# Generated by Django 5.1.5 on 2026-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bankcardprefix_bankverificationobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankverificationobservation',
            name='observed_card_prefix',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='bankverificationobservation',
            name='result',
            field=models.CharField(choices=[('invalid_card', 'Invalid Card'), ('invalid_iban', 'Invalid IBAN'), ('duplicate_card', 'Duplicate Card'), ('duplicate_iban', 'Duplicate IBAN'), ('unknown_card_prefix', 'Unknown Card Prefix'), ('unknown_iban_bank', 'Unknown IBAN Bank'), ('bank_mismatch', 'Bank Mismatch'), ('ownership_failed', 'Ownership Failed'), ('ownership_unavailable', 'Ownership Unavailable'), ('verified', 'Verified')], default='invalid_card', max_length=30),
        ),
    ]
