# Generated by Django 5.1.5 on 2026-10-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_bankverificationobservation_observed_card_prefix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankcardprefix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankverificationobservation',
            name='detected_card_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_detection_observations', to='accounts.iranianbank'),
        ),
        migrations.AddField(
            model_name='bankverificationobservation',
            name='detected_iban_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iban_detection_observations', to='accounts.iranianbank'),
        ),
        migrations.AlterField(
            model_name='bankverificationobservation',
            name='result',
            field=models.CharField(choices=[('pending', 'Pending'), ('invalid_card', 'Invalid Card'), ('invalid_iban', 'Invalid IBAN'), ('duplicate_card', 'Duplicate Card'), ('duplicate_iban', 'Duplicate IBAN'), ('unknown_card_prefix', 'Unknown Card Prefix'), ('unknown_iban_bank', 'Unknown IBAN Bank'), ('bank_mismatch', 'Bank Mismatch'), ('ownership_failed', 'Ownership Failed'), ('ownership_unavailable', 'Ownership Unavailable'), ('verified', 'Verified')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='bankverificationobservation',
            index=models.Index(fields=['observed_card_prefix', 'created_at'], name='accounts_ba_observe_bb6099_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankcardprefix',
            constraint=models.UniqueConstraint(fields=('prefix',), name='unique_bank_card_prefix'),
        ),
    ]
