# Generated by Django 5.1.5 on 2026-09-19 13:02

import apps.admin_panel.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.admin_panel.managers.AdminUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admin_panel.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'revoked_at'], name='admin_panel_admin_i_3b2244_idx'), models.Index(fields=['expires_at'], name='admin_panel_expires_147ec6_idx')],
            },
        ),
    ]
