# Generated by Django 5.1.5 on 2026-09-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'کاربر مدیر', 'verbose_name_plural': 'کاربران مدیر'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'مدیر ارشد'), ('admin', 'مدیر')], default='admin', max_length=20),
        ),
    ]
