# Generated by Django 5.1.5 on 2026-09-27 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_remove_asset_assets_asset_symbol_71b57b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('normalized_address', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('cooling_down', 'Cooling down'), ('active', 'Active'), ('disabled', 'Disabled'), ('blocked', 'Blocked'), ('revoked', 'Revoked')], default='pending_confirmation', max_length=24)),
                ('verification_method', models.CharField(choices=[('security_confirmation', 'Security confirmation'), ('ownership_signature', 'Ownership signature'), ('admin_verified', 'Admin verified')], default='security_confirmation', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
                ('confirmation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_addresses', to='assets.assetnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Address',
                'verbose_name_plural': 'Withdrawal Addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='withdrawals_user_id_a98d6d_idx'), models.Index(fields=['user', 'network'], name='withdrawals_user_id_e858df_idx'), models.Index(fields=['network', 'status'], name='withdrawals_network_ccf89a_idx'), models.Index(fields=['normalized_address'], name='withdrawals_normali_5fa7a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'network', 'normalized_address', 'memo'), name='unique_user_network_withdrawal_address')],
            },
        ),
    ]
