# Generated by Django 5.1.5 on 2026-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaladdress',
            name='confirmation_challenge_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
