# Generated by Django 5.1.5 on 2026-10-07 09:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_bankcardprefix_unique_together_and_more'),
        ('transactions', '0004_remove_transaction_transaction_referen_2a6622_idx_and_more'),
        ('withdrawals', '0002_withdrawaladdress_confirmation_challenge_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TomanWithdrawalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('receivable', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('estimate_token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('estimate_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('estimated', 'Estimated'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='estimated', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('provider_code', models.CharField(blank=True, default='', max_length=64)),
                ('provider_message', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toman_withdrawal_attempts', to='accounts.bankaccount')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='toman_withdrawal_attempt', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toman_withdrawal_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='toman_wd_user_status_idx'), models.Index(fields=['user', 'created_at'], name='toman_wd_user_created_idx'), models.Index(fields=['expires_at', 'status'], name='toman_wd_exp_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='unique_user_toman_withdrawal_idempotency')],
            },
        ),
    ]
