# Generated by Django 5.1.5 on 2026-09-06 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'KYC Application', 'verbose_name_plural': 'KYC Applications'},
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='level',
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/identity/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to='kyc/selfie/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
