# Generated by Django 5.1.5 on 2026-09-16 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='basic_info_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='basic_info_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='basic_info_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_info_kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='basic_info_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='basic_info_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['basic_info_status'], name='kyc_kycappl_basic_i_eb2c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['identity_status'], name='kyc_kycappl_identit_ffc8ab_idx'),
        ),
    ]
