# Generated by Django 5.1.5 on 2026-09-20 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_adminuser_options_alter_adminuser_role'),
        ('kyc', '0003_kycapplication_basic_info_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست احراز هویت', 'verbose_name_plural': 'درخواست\u200cهای احراز هویت'},
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='basic_info_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basic_info_kyc_reviews', to='admin_panel.adminuser'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='basic_info_status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identity_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_kyc_reviews', to='admin_panel.adminuser'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='identity_status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to='admin_panel.adminuser'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال تکمیل'), ('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='not_started', max_length=20),
        ),
    ]
