# Generated by Django 5.1.5 on 2026-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
