# Generated by Django 5.1.5 on 2026-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycapplication_father_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycapplication',
            old_name='identity_document',
            new_name='identity_document_back',
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='identity_document_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/identity/%Y/%m/%d/'),
        ),
    ]
