# Generated by Django 5.1.5 on 2026-09-01 07:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('execution_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('total', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='assets.asset')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='trades_trad_user_id_bf6c4d_idx'), models.Index(fields=['asset', 'created_at'], name='trades_trad_asset_i_02ed9c_idx')],
            },
        ),
    ]
