# Generated by Django 5.1.5 on 2026-10-06 08:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_bankcardprefix_unique_together_and_more'),
        ('transactions', '0004_remove_transaction_transaction_referen_2a6622_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=24)),
                ('currency', models.CharField(default='IRT', max_length=8)),
                ('gateway', models.CharField(blank=True, choices=[('', 'Unknown'), ('zarinpal', 'Zarinpal')], default='', max_length=32)),
                ('gateway_authority', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gateway_code', models.CharField(blank=True, default='', max_length=64)),
                ('gateway_message', models.TextField(blank=True, default='')),
                ('payment_url', models.URLField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('redirect_ready', 'Redirect Ready'), ('callback_received', 'Callback Received'), ('verifying', 'Verifying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='accounts.bankaccount')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempt', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_c07b7a_idx'), models.Index(fields=['gateway', 'gateway_authority'], name='payments_pa_gateway_ab5e95_idx'), models.Index(fields=['gateway', 'gateway_reference'], name='payments_pa_gateway_3e0f09_idx'), models.Index(fields=['created_at'], name='payments_pa_created_e831f4_idx')],
            },
        ),
    ]
