# Generated by Django 5.1.5 on 2026-10-06 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_bankcardprefix_unique_together_and_more'),
        ('payments', '0001_initial'),
        ('transactions', '0004_remove_transaction_transaction_referen_2a6622_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='gateway_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='gateway',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('nexpal', 'NexPal'), ('zarinpal', 'Zarinpal')], default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['invoice_id'], name='payments_pa_invoice_cbdce0_idx'),
        ),
    ]
