# Generated by Django 5.1.5 on 2026-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('trade', 'Trading'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('verification', 'Verification'), ('bank', 'Bank'), ('security', 'Security'), ('technical', 'Technical'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
